Repository googleapis/java-websecurityscanner, pull requests merged in 2020-09, with the labels that each got.

#203 chore: regenerate README
  README.md
  synth.metadata
Labels: api: websecurityscanner, cla: yes, context: none

#210 chore: regenerate common templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  .kokoro/release/stage.cfg
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full

#215 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#224 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#226 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: websecurityscanner, automerge, cla: yes

#228 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full

#233 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full
