Repository googleapis/java-websecurityscanner, pull requests merged in 2020-06, with the labels that each got.

#141 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#134 fix: restore GAPIC v2 retry configs
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1beta/WebSecurityScannerClient.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1beta/WebSecurityScannerSettings.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1beta/package-info.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1beta/stub/GrpcWebSecurityScannerStub.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1beta/stub/WebSecurityScannerStub.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1beta/stub/WebSecurityScannerStubSettings.java
  google-cloud-websecurityscanner/src/test/java/com/google/cloud/websecurityscanner/v1beta/WebSecurityScannerClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#144 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#143 chore: regenerate with updated protoc
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/CrawledUrl.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/CreateScanConfigRequest.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/DeleteScanConfigRequest.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/Finding.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/FindingTypeStats.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/GetFindingRequest.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/GetScanConfigRequest.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/GetScanRunRequest.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListCrawledUrlsRequest.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListCrawledUrlsResponse.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListFindingTypeStatsRequest.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListFindingTypeStatsResponse.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListFindingsRequest.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListFindingsResponse.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListScanConfigsRequest.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListScanConfigsResponse.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListScanRunsRequest.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ListScanRunsResponse.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/OutdatedLibrary.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ScanConfig.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ScanRun.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/StartScanRunRequest.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/StopScanRunRequest.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/UpdateScanConfigRequest.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/ViolatingResource.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/VulnerableHeaders.java
  proto-google-cloud-websecurityscanner-v1alpha/src/main/java/com/google/cloud/websecurityscanner/v1alpha/Xss.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/CrawledUrl.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/CreateScanConfigRequest.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/DeleteScanConfigRequest.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/Finding.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/FindingTypeStats.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/Form.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/GetFindingRequest.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/GetScanConfigRequest.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/GetScanRunRequest.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/ListCrawledUrlsRequest.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/ListCrawledUrlsResponse.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/ListFindingTypeStatsRequest.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/ListFindingTypeStatsResponse.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/ListFindingsRequest.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/ListFindingsResponse.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/ListScanConfigsRequest.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/ListScanConfigsResponse.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/ListScanRunsRequest.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/ListScanRunsResponse.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/OutdatedLibrary.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/ScanConfig.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/ScanConfigError.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/ScanRun.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/ScanRunErrorTrace.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/ScanRunWarningTrace.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/StartScanRunRequest.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/StopScanRunRequest.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/UpdateScanConfigRequest.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/ViolatingResource.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/VulnerableHeaders.java
  proto-google-cloud-websecurityscanner-v1beta/src/main/java/com/google/cloud/websecurityscanner/v1beta/Xss.java
  synth.metadata
Labels: automerge, cla: yes, context: full

#146 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#148 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#153 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#159 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#166 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-websecurityscanner/pom.xml
  grpc-google-cloud-websecurityscanner-v1/pom.xml
  grpc-google-cloud-websecurityscanner-v1alpha/pom.xml
  grpc-google-cloud-websecurityscanner-v1beta/pom.xml
  pom.xml
  proto-google-cloud-websecurityscanner-v1/pom.xml
  proto-google-cloud-websecurityscanner-v1alpha/pom.xml
  proto-google-cloud-websecurityscanner-v1beta/pom.xml
Labels: cla: yes

#169 fix: migrate retry settings to grpc_service_config
  README.md
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1/stub/WebSecurityScannerStubSettings.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/WebSecurityScannerClient.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/WebSecurityScannerSettings.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/package-info.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/stub/GrpcWebSecurityScannerStub.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/stub/WebSecurityScannerStub.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/stub/WebSecurityScannerStubSettings.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1beta/WebSecurityScannerClient.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1beta/WebSecurityScannerSettings.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1beta/package-info.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1beta/stub/GrpcWebSecurityScannerStub.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1beta/stub/WebSecurityScannerStub.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1beta/stub/WebSecurityScannerStubSettings.java
  google-cloud-websecurityscanner/src/test/java/com/google/cloud/websecurityscanner/v1alpha/WebSecurityScannerClientTest.java
  google-cloud-websecurityscanner/src/test/java/com/google/cloud/websecurityscanner/v1beta/WebSecurityScannerClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: partial

#179 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
