Repository googleapis/java-websecurityscanner, pull requests merged in 2021-02, with the labels that each got.

#348 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: websecurityscanner, automerge, cla: yes

#355 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: websecurityscanner, automerge, cla: yes

#361 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/auto-release.yaml
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  LICENSE
  synth.metadata
Labels: api: websecurityscanner, cla: yes, context: full

#363 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: websecurityscanner, automerge, cla: yes

#366 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: websecurityscanner, automerge, cla: yes

#365 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full

#370 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: websecurityscanner, automerge, cla: yes

#371 chore: update gapic-generator-java to 0.0.20
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1/stub/GrpcWebSecurityScannerStub.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/stub/GrpcWebSecurityScannerStub.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1beta/stub/GrpcWebSecurityScannerStub.java
  google-cloud-websecurityscanner/src/test/java/com/google/cloud/websecurityscanner/v1/MockWebSecurityScannerImpl.java
  google-cloud-websecurityscanner/src/test/java/com/google/cloud/websecurityscanner/v1alpha/MockWebSecurityScannerImpl.java
  google-cloud-websecurityscanner/src/test/java/com/google/cloud/websecurityscanner/v1beta/MockWebSecurityScannerImpl.java
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full

#372 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full

#374 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full

#375 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full

#376 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full

#378 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1/gapic_metadata.json
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/gapic_metadata.json
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1beta/gapic_metadata.json
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full

#382 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: websecurityscanner, automerge, cla: yes

#383 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: websecurityscanner, automerge, cla: yes

#385 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: websecurityscanner, automerge, cla: yes

#391 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: websecurityscanner, automerge, cla: yes
