Repository googleapis/java-websecurityscanner, pull requests merged in 2021-09, with the labels that each got.

#534 ci: removing linkage-monitor from the required checks
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: websecurityscanner, automerge, context: full

#542 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: websecurityscanner, automerge

#545 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/workflows/ci.yaml
  README.md
  google-cloud-websecurityscanner-bom/pom.xml
  google-cloud-websecurityscanner/pom.xml
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1/stub/WebSecurityScannerStubSettings.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1alpha/stub/WebSecurityScannerStubSettings.java
  google-cloud-websecurityscanner/src/main/java/com/google/cloud/websecurityscanner/v1beta/stub/WebSecurityScannerStubSettings.java
  owlbot.py
  pom.xml
  proto-google-cloud-websecurityscanner-v1alpha/clirr-ignored-differences.xml
  proto-google-cloud-websecurityscanner-v1beta/clirr-ignored-differences.xml
  renovate.json
  versions.txt
Labels: cla: yes, api: websecurityscanner, automerge

#554 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, kokoro:force-run, api: websecurityscanner, automerge

#522 chore: update gapic-generator-java version to 2.1.0
  synth.metadata
Labels: cla: yes, api: websecurityscanner, context: full

#566 chore: make owlbot check required
  .github/sync-repo-settings.yaml
  README.md
Labels: cla: yes, api: websecurityscanner

#560 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: websecurityscanner, automerge

#576 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: websecurityscanner, automerge
