Repository googleapis/java-websecurityscanner, pull requests merged in 2021-05, with the labels that each got.

#442 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: websecurityscanner, automerge, cla: yes

#443 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: none

#446 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full

#453 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: websecurityscanner, automerge, cla: yes

#454 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full

#456 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: websecurityscanner, automerge, cla: yes

#457 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full

#459 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full

#462 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full

#465 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: websecurityscanner, automerge, cla: yes
