Repository googleapis/java-websecurityscanner, pull requests merged in 2021-08, with the labels that each got.

#503 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: websecurityscanner, automerge, context: full

#512 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: websecurityscanner, automerge

#517 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: websecurityscanner, automerge

#519 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, kokoro:force-run, api: websecurityscanner, automerge, context: full

#521 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: websecurityscanner, automerge

#524 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: websecurityscanner, automerge

#525 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: websecurityscanner, automerge

#531 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: websecurityscanner, automerge

#532 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: websecurityscanner, automerge

#539 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: websecurityscanner, automerge
